/*
 * generated by Xtext
 */
package org.openstoryboards.jsonschemadsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JsonSchemaDslRuntimeModule extends org.openstoryboards.jsonschemadsl.AbstractJsonSchemaDslRuntimeModule {

}
