/*
* generated by Xtext
*/
package org.openstoryboards.jsonschemadsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class JsonSchemaDslStandaloneSetup extends JsonSchemaDslStandaloneSetupGenerated{

	public static void doSetup() {
		new JsonSchemaDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

