/*
 * generated by Xtext
 */
package org.openstoryboards.jsonschemadsl.ui.contentassist

import org.openstoryboards.jsonschemadsl.ui.contentassist.AbstractJsonSchemaDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class JsonSchemaDslProposalProvider extends AbstractJsonSchemaDslProposalProvider {
}
