/*
 * generated by Xtext
 */
package org.openstoryboards.jsonschemadsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JsonSchemaDslUiModule extends org.openstoryboards.jsonschemadsl.ui.AbstractJsonSchemaDslUiModule {
	public JsonSchemaDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
