/*
* generated by Xtext
*/
package org.openstoryboards.jsonschemadsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class JsonSchemaDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.openstoryboards.jsonschemadsl.ui.internal.JsonSchemaDslActivator.getInstance().getInjector("org.openstoryboards.jsonschemadsl.JsonSchemaDsl");
	}
	
}
